"""Data-movement runbook: offline artifacts that direct the move.

pgrecon never connects to a database, so it does not move rows; it
generates the exact artifacts the move needs instead. The mover
configuration targets ora2pg's data-only mode - any mover works, but
that one is free and everywhere - and the validation SQL runs on both
engines so the cutover ends with evidence instead of hope.
"""

import sqlite3
from pathlib import Path

_NUMERIC = {"NUMBER", "FLOAT", "INTEGER", "DECIMAL"}


def _tables(conn: sqlite3.Connection) -> list[tuple[str, str | None]]:
    """(table_name, first numeric column) for every real table, the
    numeric column giving each side a cheap content spot-check."""
    rows = conn.execute(
        "SELECT t.table_name,"
        " (SELECT c.column_name FROM columns c"
        "   WHERE c.owner = t.owner AND c.table_name = t.table_name"
        "   AND UPPER(c.data_type) IN ({}) ORDER BY c.position LIMIT 1)"
        " FROM tables t WHERE t.table_name NOT LIKE 'MLOG$%'"
        " AND t.table_name NOT LIKE 'RUPD$%'"
        " ORDER BY t.table_name".format(", ".join(f"'{t}'" for t in _NUMERIC))
    ).fetchall()
    return [(r[0], r[1]) for r in rows]


def _mviews(conn: sqlite3.Connection) -> list[str]:
    try:
        return [
            r[0]
            for r in conn.execute("SELECT mview_name FROM mviews ORDER BY mview_name")
        ]
    except sqlite3.OperationalError:
        return []


def write_runbook(db: Path, out_dir: Path) -> list[str]:
    """Write the runbook artifacts; returns the file names written."""
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    try:
        meta = dict(conn.execute("SELECT key, value FROM meta"))
        tables = _tables(conn)
        mviews = _mviews(conn)
        sequences = [
            (r["sequence_name"], r["last_number"])
            for r in conn.execute(
                "SELECT sequence_name, last_number FROM sequences"
                " ORDER BY sequence_name"
            )
        ]
    finally:
        conn.close()
    schema = meta.get("schema", "SCHEMA")

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    def emit(name: str, text: str) -> None:
        (out_dir / name).write_text(text, encoding="ascii", newline="\n")
        written.append(name)

    emit(
        "apply_schema.sh",
        "\n".join(
            [
                "#!/bin/sh",
                "# Apply the converted schema in dependency-safe order.",
                "# Generated by pgrecon runbook; review before running.",
                "# Usage: PGDATABASE=target [PGHOST=... PGUSER=...] sh apply_schema.sh",
                "set -u",
                "LOG=apply_schema.log",
                ': > "$LOG"',
                "apply() {",
                '  if [ -f "$1" ]; then',
                '    echo "-- FILE $1" >> "$LOG"',
                '    psql -v ON_ERROR_STOP=0 -qX -f "$1" >> "$LOG" 2>&1',
                "  else",
                '    echo "-- MISSING $1 (skipped)" >> "$LOG"',
                "  fi",
                "}",
                "# 1. Structure from pgrecon convert.",
                "apply schema_pg.sql",
                "# 2. Flattened packages from the commercial tier, if used.",
                "apply packages.sql",
                "# 3. Reviewed drafts, each one deliberately - never blind:",
                '#    for f in drafts/*.sql; do apply "$f"; done',
                "ERRORS=$(grep -c 'ERROR:' \"$LOG\" || true)",
                'echo "applied; errors in $LOG: $ERRORS"',
                "echo 'Anything above zero: read the log next to the'",
                "echo 'residue report before touching data movement.'",
                "",
            ]
        ),
    )

    emit(
        "ora2pg_data.conf",
        "\n".join(
            [
                "# Data-only ora2pg configuration generated by pgrecon.",
                "# Fill the two DSN lines, review, then run:",
                "#   ora2pg -c ora2pg_data.conf",
                "# Schema structure comes from pgrecon convert, so this",
                "# configuration moves rows and nothing else.",
                "",
                "ORACLE_DSN      dbi:Oracle:host=FILL_ME;"
                "service_name=FILL_ME;port=1521",
                "ORACLE_USER     FILL_ME",
                "ORACLE_PWD      FILL_ME",
                "",
                f"SCHEMA          {schema}",
                "TYPE            COPY",
                "PG_DSN          dbi:Pg:dbname=FILL_ME;host=FILL_ME;port=5432",
                "PG_USER         FILL_ME",
                "PG_PWD          FILL_ME",
                "",
                "DISABLE_TRIGGERS 1",
                "TRUNCATE_TABLE  1",
                "DATA_LIMIT      10000",
                "",
            ]
        ),
    )

    def count_select(name: str, numeric: str | None, lower: bool) -> str:
        ident = name.lower() if lower else f'"{name}"'
        spot = (
            f", SUM({numeric.lower() if lower else numeric}) AS spot_sum"
            if numeric
            else ", NULL AS spot_sum"
        )
        return f"SELECT '{name}' AS tab, COUNT(*) AS rows{spot} FROM {ident}"

    emit(
        "validate_rowcounts_oracle.sql",
        "-- Run on the Oracle side after the freeze, before cutover.\n"
        + "\nUNION ALL\n".join(count_select(t, n, lower=False) for t, n in tables)
        + "\nORDER BY 1;\n",
    )
    emit(
        "validate_rowcounts_postgres.sql",
        "-- Run on the PostgreSQL side after the load; compare with the\n"
        "-- Oracle output line by line. spot_sum is a first-numeric-column\n"
        "-- checksum: equal counts with unequal sums means damaged rows.\n"
        + "\nUNION ALL\n".join(count_select(t, n, lower=True) for t, n in tables)
        + "\nORDER BY 1;\n",
    )

    post_load = [
        "-- Run on PostgreSQL after the data load, in this order.",
        "",
    ]
    for seq, last in sequences:
        post_load.append(
            f"-- {seq.lower()}: Oracle last_number was {last};"
            " confirm it clears the loaded maximum."
        )
        post_load.append(
            f"SELECT setval('{seq.lower()}', GREATEST("
            f"(SELECT last_value FROM {seq.lower()}), {last or 1}));"
        )
    post_load.append("")
    for mv in mviews:
        post_load.append(f"REFRESH MATERIALIZED VIEW {mv.lower()};")
    post_load.append("")
    for t, _ in tables:
        post_load.append(f"ANALYZE {t.lower()};")
    post_load.append("")
    emit("post_load_postgres.sql", "\n".join(post_load))

    emit(
        "cutover_checklist.md",
        "\n".join(
            [
                f"# Cutover checklist: {schema}",
                "",
                "1. Freeze writes on the Oracle side; note the time.",
                "2. Apply the pgrecon-converted schema to the empty target",
                "   database and confirm zero errors.",
                "3. Move the rows (ora2pg_data.conf is ready for ora2pg;",
                "   any mover that honors the freeze works).",
                "4. Run validate_rowcounts_oracle.sql on Oracle and",
                "   validate_rowcounts_postgres.sql on PostgreSQL; compare",
                "   line by line. Any difference stops the cutover.",
                "5. Run post_load_postgres.sql: sequence alignment first,",
                "   materialized view refresh, then ANALYZE.",
                "6. Re-point one read-only consumer and let it soak before",
                "   moving writers.",
                "7. Keep the Oracle side frozen and reachable until the",
                "   agreed fallback window closes.",
                "",
                "Everything the converter refused is in the residue report;",
                "nothing on that list is covered by this checklist.",
                "",
            ]
        ),
    )
    return written
