"""Orchestrate emitting PostgreSQL schema DDL from the inventory's facts.

The converter reads the same fact tables the rules do and writes
plain DDL: tables with typed columns, then primary keys, unique
constraints, checks, and foreign keys in dependency-safe order.
Anything it cannot convert faithfully becomes a residue item naming
the object and the reason - wrong DDL is never emitted silently.

Identifiers are folded to PostgreSQL's lowercase convention and
quoted only when they need it, which is what migrated applications
almost always want.
"""

import sqlite3
from dataclasses import dataclass
from pathlib import Path

from pgrecon.convert.code import _emit_code
from pgrecon.convert.constraints import _emit_checks, _emit_foreign_keys, _emit_keys
from pgrecon.convert.extras import _emit_db_links, _emit_sequences, _emit_synonyms
from pgrecon.convert.identifiers import ident as ident
from pgrecon.convert.indexes import _emit_indexes
from pgrecon.convert.residue import Residue as Residue
from pgrecon.convert.tables import emit_tables
from pgrecon.convert.triggers import _emit_triggers
from pgrecon.convert.views import _emit_views


@dataclass(frozen=True)
class Conversion:
    sql: str
    residue: tuple[Residue, ...]
    tables: int
    constraints: int
    indexes: int
    views: int
    partitions: int
    sequences: int
    synonyms: int
    db_links: int
    routines: int
    triggers: int


def convert_schema(db: Path) -> Conversion:
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    try:
        return _convert(conn)
    finally:
        conn.close()


def _convert(conn: sqlite3.Connection) -> Conversion:
    out: list[str] = []
    residue: list[Residue] = []
    constraint_count = 0

    out.append("-- Generated by pgrecon convert: schema structure from the")
    out.append("-- inventory's dictionary facts. Review the residue report")
    out.append("-- for everything that needs a human decision.")
    out.append("")

    # Tables and the columns that actually made it into the DDL; the
    # constraint emitters validate against this so nothing references
    # a table or column that does not exist on the target. Dropped
    # columns are tracked so a check condition naming one declines.
    emitted: dict[tuple[str, str], set[str]] = {}
    dropped: dict[tuple[str, str], set[str]] = {}

    # Sequences first: column defaults may call nextval on them, and
    # PostgreSQL resolves that at CREATE TABLE time.
    sequence_count, sequence_names = _emit_sequences(conn, out, residue)

    table_count, partition_count = emit_tables(conn, out, residue, emitted, dropped)

    constraint_count += _emit_keys(conn, out, residue, emitted)
    constraint_count += _emit_checks(conn, out, residue, emitted, dropped)
    constraint_count += _emit_foreign_keys(conn, out, residue, emitted)
    index_count = _emit_indexes(conn, out, residue, emitted)
    view_count, created_views = _emit_views(conn, out, residue, emitted, dropped)
    synonym_count, synonym_names = _emit_synonyms(
        conn, out, residue, emitted, created_views
    )
    routine_count = _emit_code(
        conn, out, residue, emitted, created_views, sequence_names, synonym_names
    )
    trigger_count = _emit_triggers(
        conn,
        out,
        residue,
        emitted,
        sequence_names,
        {t for (_, t) in emitted} | created_views | synonym_names,
        frozenset(
            (r["name"] or "").upper()
            for r in conn.execute("SELECT name FROM objects WHERE type = 'PROCEDURE'")
        ),
        {
            (r["owner"] or "").upper()
            for r in conn.execute("SELECT DISTINCT owner FROM objects")
        },
        {
            (r["name"] or "").upper()
            for r in conn.execute(
                "SELECT name FROM objects WHERE type IN ('FUNCTION', 'PROCEDURE')"
            )
        },
        {
            (r["name"] or "").upper()
            for r in conn.execute("SELECT name FROM objects WHERE type = 'PACKAGE'")
        },
    )
    link_count = _emit_db_links(conn, out, residue)

    return Conversion(
        "\n".join(out),
        tuple(residue),
        table_count,
        constraint_count,
        index_count,
        view_count,
        partition_count,
        sequence_count,
        synonym_count,
        link_count,
        routine_count,
        trigger_count,
    )


def residue_report(residue: tuple[Residue, ...]) -> str:
    """The residue as a reviewable text report."""
    if not residue:
        return "Nothing was left behind: every fact converted cleanly.\n"
    lines = [
        "Residue: what the converter declined to convert, and why.",
        "Each line needs a human decision before the schema is complete.",
        "",
    ]
    for r in residue:
        lines.append(f"{r.kind:12} {r.owner}.{r.object_name}: {r.reason}")
    lines.append("")
    return "\n".join(lines)
