"""Emit PostgreSQL schema DDL from the inventory's structured facts.

The converter reads the same fact tables the rules do and writes
plain DDL: tables with typed columns, then primary keys, unique
constraints, checks, and foreign keys in dependency-safe order.
Anything it cannot convert faithfully becomes a residue item naming
the object and the reason - wrong DDL is never emitted silently.

Identifiers are folded to PostgreSQL's lowercase convention and
quoted only when they need it, which is what migrated applications
almost always want.
"""

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from pgrecon.convert.typemap import map_type

_PLAIN_IDENT = re.compile(r"^[a-z_][a-z0-9_]*$")

_RESERVED = {
    "all",
    "analyse",
    "analyze",
    "and",
    "any",
    "array",
    "as",
    "asc",
    "asymmetric",
    "both",
    "case",
    "cast",
    "check",
    "collate",
    "column",
    "constraint",
    "create",
    "current_date",
    "current_role",
    "current_time",
    "current_timestamp",
    "current_user",
    "default",
    "deferrable",
    "desc",
    "distinct",
    "do",
    "else",
    "end",
    "except",
    "false",
    "fetch",
    "for",
    "foreign",
    "from",
    "grant",
    "group",
    "having",
    "in",
    "initially",
    "intersect",
    "into",
    "lateral",
    "leading",
    "limit",
    "localtime",
    "localtimestamp",
    "not",
    "null",
    "offset",
    "on",
    "only",
    "or",
    "order",
    "placing",
    "primary",
    "references",
    "returning",
    "select",
    "session_user",
    "some",
    "symmetric",
    "table",
    "then",
    "to",
    "trailing",
    "true",
    "union",
    "unique",
    "user",
    "using",
    "variadic",
    "when",
    "where",
    "window",
    "with",
}

_NOT_NULL_CONDITION = re.compile(
    r'^"?[A-Za-z0-9_$#]+"?\s+IS\s+NOT\s+NULL$', re.IGNORECASE
)


@dataclass(frozen=True)
class Residue:
    """One thing the converter declined to convert, and why."""

    owner: str
    object_name: str
    kind: str
    reason: str


@dataclass(frozen=True)
class Conversion:
    sql: str
    residue: tuple[Residue, ...]
    tables: int
    constraints: int


def ident(name: str) -> str:
    """Fold to lowercase; quote only when the result needs it."""
    lowered = name.lower()
    if _PLAIN_IDENT.match(lowered) and lowered not in _RESERVED:
        return lowered
    return '"' + name.replace('"', '""') + '"'


def _columns(conn: sqlite3.Connection, owner: str, table: str) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT column_name, data_type, data_length, data_precision,"
        " data_scale, nullable FROM columns"
        " WHERE owner = ? AND table_name = ? ORDER BY position",
        (owner, table),
    ).fetchall()


def _partition_clause(
    conn: sqlite3.Connection, owner: str, table: str
) -> tuple[str | None, str | None]:
    """The PARTITION BY clause and a residue reason, either may be None."""
    part = conn.execute(
        "SELECT partitioning_type, interval FROM part_tables"
        " WHERE owner = ? AND table_name = ?",
        (owner, table),
    ).fetchone()
    if part is None:
        return None, None
    ptype = (part["partitioning_type"] or "").upper()
    keys = [
        ident(r["column_name"])
        for r in conn.execute(
            "SELECT column_name FROM part_key_columns"
            " WHERE owner = ? AND table_name = ? ORDER BY position",
            (owner, table),
        )
    ]
    if ptype in ("RANGE", "LIST", "HASH") and keys:
        reason = (
            "partition bounds are not in the extraction yet;"
            " child partitions must be defined by hand"
        )
        if part["interval"]:
            reason = (
                "interval partitioning has no native counterpart;"
                " schedule partition creation (for example with pg_partman)"
            )
        return f" PARTITION BY {ptype} ({', '.join(keys)})", reason
    return None, f"{ptype or 'unknown'} partitioning needs a hand-designed layout"


def convert_schema(db: Path) -> Conversion:
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    try:
        return _convert(conn)
    finally:
        conn.close()


def _convert(conn: sqlite3.Connection) -> Conversion:
    out: list[str] = []
    residue: list[Residue] = []
    table_count = 0
    constraint_count = 0

    out.append("-- Generated by pgrecon convert: schema structure from the")
    out.append("-- inventory's dictionary facts. Review the residue report")
    out.append("-- for everything that needs a human decision.")
    out.append("")

    tables = conn.execute(
        "SELECT owner, table_name, temporary FROM tables" " ORDER BY owner, table_name"
    ).fetchall()

    for t in tables:
        owner, table = t["owner"], t["table_name"]
        cols = _columns(conn, owner, table)
        if not cols:
            residue.append(
                Residue(owner, table, "table", "no column facts in the inventory")
            )
            continue
        lines: list[str] = []
        for c in cols:
            mapped = map_type(
                c["data_type"], c["data_length"], c["data_precision"], c["data_scale"]
            )
            if mapped.pg_type is None:
                residue.append(
                    Residue(
                        owner,
                        f"{table}.{c['column_name']}",
                        "column",
                        mapped.note or "unmappable type",
                    )
                )
                continue
            if mapped.note is not None:
                residue.append(
                    Residue(owner, f"{table}.{c['column_name']}", "note", mapped.note)
                )
            null = "" if (c["nullable"] or "Y") == "Y" else " NOT NULL"
            lines.append(f"    {ident(c['column_name'])} {mapped.pg_type}{null}")
        if not lines:
            residue.append(
                Residue(owner, table, "table", "every column was unconvertible")
            )
            continue
        clause, part_reason = _partition_clause(conn, owner, table)
        if part_reason is not None:
            residue.append(Residue(owner, table, "partitioning", part_reason))
        if (t["temporary"] or "N") == "Y":
            residue.append(
                Residue(
                    owner,
                    table,
                    "table",
                    "global temporary table emitted as a plain table;"
                    " per-session semantics need pgtt or a redesign",
                )
            )
        out.append(f"CREATE TABLE {ident(table)} (")
        out.append(",\n".join(lines))
        out.append(f"){clause or ''};")
        out.append("")
        table_count += 1

    constraint_count += _emit_keys(conn, out, residue)
    constraint_count += _emit_checks(conn, out, residue)
    constraint_count += _emit_foreign_keys(conn, out, residue)

    return Conversion("\n".join(out), tuple(residue), table_count, constraint_count)


def _constraint_columns(conn: sqlite3.Connection, owner: str, name: str) -> list[str]:
    return [
        ident(r["column_name"])
        for r in conn.execute(
            "SELECT column_name FROM constraint_columns"
            " WHERE owner = ? AND constraint_name = ? ORDER BY position",
            (owner, name),
        )
    ]


def _emit_keys(conn: sqlite3.Connection, out: list[str], residue: list[Residue]) -> int:
    count = 0
    rows = conn.execute(
        "SELECT owner, constraint_name, table_name, type FROM constraints"
        " WHERE type IN ('P', 'U') ORDER BY type, owner, table_name, constraint_name"
    ).fetchall()
    for r in rows:
        cols = _constraint_columns(conn, r["owner"], r["constraint_name"])
        if not cols:
            residue.append(
                Residue(
                    r["owner"], r["constraint_name"], "constraint", "no column facts"
                )
            )
            continue
        kind = "PRIMARY KEY" if r["type"] == "P" else "UNIQUE"
        out.append(
            f"ALTER TABLE {ident(r['table_name'])} ADD CONSTRAINT"
            f" {ident(r['constraint_name'])} {kind} ({', '.join(cols)});"
        )
        count += 1
    if rows:
        out.append("")
    return count


def _emit_checks(
    conn: sqlite3.Connection, out: list[str], residue: list[Residue]
) -> int:
    count = 0
    rows = conn.execute(
        "SELECT c.owner, c.constraint_name, c.table_name, k.condition, k.truncated"
        " FROM constraints c JOIN check_conditions k"
        " ON k.owner = c.owner AND k.constraint_name = c.constraint_name"
        " WHERE c.type = 'C' ORDER BY c.owner, c.table_name, c.constraint_name"
    ).fetchall()
    emitted = False
    for r in rows:
        condition = (r["condition"] or "").strip()
        if not condition or _NOT_NULL_CONDITION.match(condition):
            # Column-level NOT NULL already lives on the column.
            continue
        if r["truncated"]:
            residue.append(
                Residue(
                    r["owner"],
                    r["constraint_name"],
                    "check",
                    "condition was truncated during extraction; recover it"
                    " from the source before porting",
                )
            )
            continue
        out.append(
            f"ALTER TABLE {ident(r['table_name'])} ADD CONSTRAINT"
            f" {ident(r['constraint_name'])} CHECK ({condition});"
        )
        emitted = True
        count += 1
    if emitted:
        out.append("")
    return count


def _emit_foreign_keys(
    conn: sqlite3.Connection, out: list[str], residue: list[Residue]
) -> int:
    count = 0
    rows = conn.execute(
        "SELECT owner, constraint_name, table_name, ref_owner, ref_constraint,"
        " delete_rule FROM constraints WHERE type = 'R'"
        " ORDER BY owner, table_name, constraint_name"
    ).fetchall()
    for r in rows:
        cols = _constraint_columns(conn, r["owner"], r["constraint_name"])
        ref = conn.execute(
            "SELECT table_name FROM constraints"
            " WHERE owner = ? AND constraint_name = ?",
            (r["ref_owner"], r["ref_constraint"]),
        ).fetchone()
        ref_cols = (
            _constraint_columns(conn, r["ref_owner"], r["ref_constraint"])
            if ref
            else []
        )
        if not cols or ref is None or not ref_cols:
            residue.append(
                Residue(
                    r["owner"],
                    r["constraint_name"],
                    "foreign key",
                    "referenced key is outside the extracted schema",
                )
            )
            continue
        action = ""
        if (r["delete_rule"] or "").upper() == "CASCADE":
            action = " ON DELETE CASCADE"
        elif (r["delete_rule"] or "").upper() == "SET NULL":
            action = " ON DELETE SET NULL"
        out.append(
            f"ALTER TABLE {ident(r['table_name'])} ADD CONSTRAINT"
            f" {ident(r['constraint_name'])} FOREIGN KEY ({', '.join(cols)})"
            f" REFERENCES {ident(ref['table_name'])} ({', '.join(ref_cols)}){action};"
        )
        count += 1
    if rows:
        out.append("")
    return count


def residue_report(residue: tuple[Residue, ...]) -> str:
    """The residue as a reviewable text report."""
    if not residue:
        return "Nothing was left behind: every fact converted cleanly.\n"
    lines = [
        "Residue: what the converter declined to convert, and why.",
        "Each line needs a human decision before the schema is complete.",
        "",
    ]
    for r in residue:
        lines.append(f"{r.kind:12} {r.owner}.{r.object_name}: {r.reason}")
    lines.append("")
    return "\n".join(lines)
